//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGATOriente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgregarNuevosEstudiantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgregarNuevosEstudiantes()
        {
            this.PagosEstudiantes = new HashSet<PagosEstudiantes>();
        }
    
        public int EstudianteID { get; set; }
        public string NombreCompleto { get; set; }
        public string NumeroTelefono { get; set; }
        public string Direccion { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int Edad { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Padecimientos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosEstudiantes> PagosEstudiantes { get; set; }
    }
}
