//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGATOriente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int NotificacionID { get; set; }
        public string TipoNotificacion { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaEnvio { get; set; }
    }
}
