//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGATOriente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgresoEstudiante
    {
        public int ProgresoID { get; set; }
        public string NombreEstudiante { get; set; }
        public string CambioGrado { get; set; }
        public System.DateTime FechaExamen { get; set; }
        public string NivelAlcanzado { get; set; }
    }
}
