//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado en tu aplicación.
//     Los cambios manuales en este archivo serán sobrescritos si el código es regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGATOriente.Models
{
    using System;
    using System.Collections.Generic;

    public partial class RecursosEducacionale
    {
        public int RecursoID { get; set; }
        public string Nombre { get; set; }
        public string URL { get; set; }
    }
}
