//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGATOriente.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGATOrienteDBEntities9 : DbContext
    {
        public SGATOrienteDBEntities9()
            : base("name=SGATOrienteDBEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Reporte> Reportes { get; set; }

        public System.Data.Entity.DbSet<SGATOriente.Models.Usuario> Usuarios { get; set; }
    }
}
